/** Reusable geometry/placement tools. No catalogue, live game state, IDs or macro planner. */
export { createRegionMask, capsule, elementShapes, findRegionRoute, shapesOverlap, travelClear, validShape } from './geometry.ts';
export { spreadPoints } from './placement.ts';
export { microMetrics } from './metrics.ts';
export { resolveAccessRequirements, validateRegionAccess } from './access.ts';
export type { RegionAccessInput, RegionAccessResult } from './access.ts';
export { portalStands, validatePortalReach } from './portals.ts';
export type { PortalReachInput, PortalReachResult, PortalStands } from './portals.ts';
export { inheritBoundaryPorts, pairedBoundaryPort, validateBoundaryComposition } from './boundary.ts';
export type { RegionBoundary, ChildBoundary } from './boundary.ts';
export type { SpreadPointOptions, SpreadPointResult } from './placement.ts';
export type { BuilderContext, Cell, RegionBuilder, RegionMask, RegionRandom, RegionSpec, MicroResult, BuiltRegion, Portal, RegionBrief } from './types.ts';
export { analyzeRegion, canonicalCells, cellKey, connectedComponents, findNeckCuts, growRegion, shortestCellPath } from './decomposition/analysis.ts';
export { createRegionContext } from './decomposition/context.ts';
export { DecompositionState, allocateCandidates, generatorFitness, measureState, scoreState } from './decomposition/allocation.ts';
export { buildInterfaces } from './decomposition/interfaces.ts';
export { validateDecompositionPlan } from './decomposition/validate.ts';
export { negotiatePortals } from './decomposition/negotiate.ts';
export type { CrossingTerms, NegotiatedCrossing, NegotiatedPortals, PortalPolicy } from './decomposition/negotiate.ts';
export type * from './decomposition/types.ts';
export { emitWallRun } from './building/walls.ts';
export type { WallOpening, WallRunOptions } from './building/walls.ts';
export { OUTSIDE, validateBuildingDesign } from './building/design.ts';
export type { BuildingSpace, BuildingConnection, BuildingDesign, BuildingAllocation, BuildingSide, OpeningKind } from './building/design.ts';
export { deriveBuildingBoundaries } from './building/boundaries.ts';
export type { BuildingBoundary, BuildingSpan, SpanStep } from './building/boundaries.ts';
export { placeBuildingOpenings } from './building/openings.ts';
export type { PlacedBuildingOpening, MissedBuildingOpening, BuildingOpeningResult, BuildingOpeningOptions, BuildingRunLimits } from './building/openings.ts';
export { realizeBuilding } from './building/realize.ts';
export type { BuildingRealization, BuildingRealizationOptions } from './building/realize.ts';
export { splitBuilding } from './building/pieces.ts';
export type { BuildingPiece, BuildingPieceOptions } from './building/pieces.ts';
export type { BuildingObserver, BuildingTrace } from './building/trace.ts';
export { allocateBuilding } from './building/allocation.ts';
export type { BuildingAllocationOptions, BuildingAllocationResult, BuildingAllocationSearch, BuildingAllocationScores } from './building/allocation.ts';
