// Standalone browser acceptance for the allocation-proposal inspector.
import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { chromium } from '@playwright/test';
import { createArenaServer } from '../server/index.js';
import { listen } from './helpers/listen.js';

const replayDir = await mkdtemp(path.join(os.tmpdir(), 'last-exit-decomposition-lab-'));
await mkdir('test-results', { recursive: true });
const server = await createArenaServer({ replayDir, profileSummary: false });
const base = await listen(server);
const browser = await chromium.launch({ channel: 'chrome', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1200, height: 900 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error' && !message.text().includes('404')) errors.push(message.text()); });
  await page.goto(`${base}/decomposition-lab.html`);
  await page.waitForFunction(() => window.decompositionLabDebug?.().plan, null, { timeout: 15000 });
  const initial = await page.evaluate(() => window.decompositionLabDebug());
  assert.equal(initial.plan.version, 'decomposition-1');
  const owned = new Set(initial.input.cells.map(c => `${c.x},${c.y}`));
  const allocations = [...initial.plan.pieces, ...initial.plan.residuals];
  const seen = new Set();
  for (const allocation of allocations) for (const cell of allocation.cells) {
    const id = `${cell.x},${cell.y}`;
    assert.ok(owned.has(id), `allocation cell ${id} remains inside the context`);
    assert.ok(!seen.has(id), `allocation cell ${id} has a single owner`);
    seen.add(id);
  }
  assert.deepEqual([...seen].sort(), [...owned].sort(), 'pieces and residuals partition the input context');
  await page.getByLabel('Pattern example').selectOption('ring');
  await page.waitForFunction(() => window.decompositionLabDebug().input?.id.includes('ring'));
  const ring = await page.evaluate(() => window.decompositionLabDebug());
  assert.ok(ring.plan.pieces.some(piece => piece.generator === 'courtyard-ring'), 'ring preserves its hole through the courtyard allocation when that strategy wins');
  assert.ok(ring.plan.candidates.length > ring.plan.pieces.length, 'candidate view retains competing footprints beyond selected allocations');
  assert.ok(ring.plan.diagnostics.some(item => item.status === 'rejected'), 'diagnostics retain rejected generator alternatives');
  await page.getByLabel('Canvas view').selectOption('candidates');
  const candidateSelect = page.locator('#candidate');
  const firstCandidate = await candidateSelect.inputValue();
  const secondCandidate = ring.plan.candidates.find(candidate => candidate.id !== firstCandidate);
  assert.ok(secondCandidate, 'ring example has a second candidate footprint to inspect');
  await candidateSelect.selectOption(secondCandidate.id);
  await page.waitForFunction(id => window.decompositionLabDebug().selectedCandidateId === id, secondCandidate.id);
  assert.match(await page.locator('#piece-inspector').textContent(), new RegExp(secondCandidate.id.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')), 'candidate inspector follows the selected footprint');
  await page.screenshot({ path: 'test-results/decomposition-lab-ring-candidate.png', fullPage: true });
  await page.getByLabel('Pattern example').selectOption('neck');
  await page.waitForFunction(() => window.decompositionTreeDebug?.().portfolio?.alternatives.length > 0);
  await page.getByLabel('Tree objective').selectOption('rooms');
  await page.waitForFunction(() => window.decompositionTreeDebug().portfolio.objective === 'rooms');
  const trees = await page.evaluate(() => window.decompositionTreeDebug().portfolio);
  const treeDepth = node => node.children.length ? 1 + Math.max(...node.children.map(treeDepth)) : 0;
  assert.ok(trees.alternatives.some(tree => treeDepth(tree.root) >= 2), 'room objective explores child subdivisions');
  assert.ok(trees.alternatives.length > 1, 'tree explorer retains alternatives');
  await page.getByLabel('Retained alternative').selectOption('1');
  assert.equal(await page.evaluate(() => window.decompositionTreeDebug().alternativeIndex), 1);
  await page.locator('#tree-nodes button').last().click();
  assert.match(await page.locator('#tree-detail').textContent(), /Depth [12]/, 'branch selection exposes hierarchy');
  await page.screenshot({ path: 'test-results/decomposition-trees.png', fullPage: true });
  const treeDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download trees JSON' }).click();
  const treeFile = await treeDownload;
  assert.deepEqual(JSON.parse(await readFile(await treeFile.path(), 'utf8')), trees);
  await page.getByLabel('Tree objective').selectOption('preserve');
  await page.waitForFunction(() => window.decompositionTreeDebug().portfolio.objective === 'preserve');
  const preserved = await page.evaluate(() => window.decompositionTreeDebug().portfolio.alternatives[0].root);
  assert.notDeepEqual(preserved, trees.alternatives[0].root, 'objective presets choose different trees');
  await page.waitForFunction(() => window.decompositionLabDebug().input?.id.includes('neck'));
  const balanced = await page.evaluate(() => window.decompositionLabDebug().plan);
  await page.getByLabel('Allocation policy').selectOption('fewer');
  await page.waitForFunction(() => window.decompositionLabDebug().plan?.policy?.piecePenalty === 200);
  const fewer = await page.evaluate(() => window.decompositionLabDebug().plan);
  assert.notEqual(JSON.stringify(balanced.pieces), JSON.stringify(fewer.pieces), 'meaningful policy presets produce different allocation geometry');
  assert.ok(fewer.pieces.length < balanced.pieces.length, 'prefer-fewer-pieces preset reduces the neck plan count');
  await page.getByText('Advanced policy', { exact: true }).click();
  await page.getByLabel('Beam search width').fill('1');
  await page.waitForFunction(() => window.decompositionLabDebug().plan?.search?.beamWidth === 1);
  assert.match(await page.locator('#status').textContent(), /allocation is the same winner|Allocation changed/i, 'automatic slider recompute reports whether the allocation changed');
  await page.getByLabel('Canvas view').selectOption('depth');
  await page.waitForFunction(() => window.decompositionLabDebug().analysis?.depth?.length > 0);
  await page.getByLabel('Canvas view').selectOption('selected');
  await page.screenshot({ path: 'test-results/decomposition-lab-neck-selected.png', fullPage: true });
  const downloadable = await page.evaluate(() => window.decompositionLabDebug().plan);
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download JSON' }).click();
  const file = await download;
  assert.match(file.suggestedFilename(), /^decomposition-.*\.json$/);
  assert.deepEqual(JSON.parse(await readFile(await file.path(), 'utf8')), JSON.parse(JSON.stringify(downloadable)), 'download preserves the full JSON artifact');
  await page.getByLabel('Load RegionContextInput JSON').setInputFiles({ name: 'broken.json', mimeType: 'application/json', buffer: Buffer.from('{not json') });
  await page.waitForFunction(() => document.querySelector('#status').textContent.startsWith('Import rejected:'));
  assert.match(await page.locator('#status').textContent(), /Import rejected:/, 'malformed context import reports rejection');
  assert.ok((await page.evaluate(() => window.decompositionLabDebug().input.id)).includes('neck'), 'rejected imports keep the last valid context');
  const imported = { id: 'browser-imported-context', cellSize: 40, cells: [{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 0, y: 1 }, { x: 1, y: 1 }] };
  await page.getByLabel('Load RegionContextInput JSON').setInputFiles({ name: 'context.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(imported)) });
  await page.waitForFunction(() => window.decompositionLabDebug().input?.id === 'browser-imported-context');
  await page.getByRole('slider', { name: /^Prefer fewer pieces/ }).fill('17');
  await page.waitForFunction(() => window.decompositionLabDebug().plan?.policy?.piecePenalty === 17);
  assert.equal(await page.evaluate(() => window.decompositionLabDebug().input.id), imported.id, 'generating a new policy preserves the imported context');
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, 'compact inspector has no horizontal overflow');
  await page.screenshot({ path: 'test-results/decomposition-lab-compact.png', fullPage: true });
  assert.equal(errors.length, 0, errors.join('\n'));
} finally {
  await browser.close();
  await server.close();
  await rm(replayDir, { recursive: true, force: true });
}
