// Standalone acceptance for the decomposition-to-physical-geometry demonstration.
import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { chromium } from '@playwright/test';
import { createArenaServer } from '../server/index.js';
import { listen } from './helpers/listen.js';

const replayDir = await mkdtemp(path.join(os.tmpdir(), 'last-exit-generation-demo-'));
await mkdir('test-results', { recursive: true });
const server = await createArenaServer({ replayDir, profileSummary: false });
const base = await listen(server), browser = await chromium.launch({ channel: 'chrome', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1200, height: 900 } }), errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error' && !message.text().includes('404')) errors.push(message.text()); });
  await page.goto(`${base}/generation-demo.html`);
  await page.waitForFunction(() => window.generationDemoDebug?.().result, null, { timeout: 15000 });
  await assert.doesNotReject(() => page.getByText('ownership boundary', { exact: false }).waitFor());
  const initial = await page.evaluate(() => window.generationDemoDebug());
  assert.equal(initial.result.version, 'realized-decomposition-1');
  assert.ok(initial.result.regions.length >= 3, 'default neck realizes three or more child regions');
  assert.ok(initial.result.portals.length >= 2, 'default neck has connected portals');
  for (const assignment of initial.result.assignments.filter(a => a.role === 'room')) assert.ok(initial.result.regions.find(r => r.spec.id === assignment.pieceId).elements.some(e => e.template.encloses), 'room child has actual roof geometry');
  await page.screenshot({ path: 'test-results/generation-demo-warehouse.png', fullPage: true });
  await page.getByRole('button', { name: 'Region', exact: true }).click();
  assert.deepEqual(await page.evaluate(() => window.generationDemoDebug().stage), 'region');
  assert.equal(await page.evaluate(() => window.generationDemoDebug().walker), null, 'region stage has no walker');
  await page.getByRole('button', { name: 'Decomposition', exact: true }).click();
  assert.equal(await page.evaluate(() => window.generationDemoDebug().walker), null, 'decomposition stage has no walker');
  await page.getByRole('button', { name: 'Generated', exact: true }).click();
  assert.equal(await page.evaluate(() => window.generationDemoDebug().walker), null, 'generated stage has no walker');
  await page.getByRole('button', { name: 'Walk', exact: true }).click();
  assert.ok(await page.evaluate(() => window.generationDemoDebug().walker), 'walk stage creates the walker');
  await page.getByLabel('Room contents').selectOption('ruins');
  await page.waitForFunction(() => window.generationDemoDebug().result?.assignments.some(a => a.builder === 'ruins'));
  const ruins = await page.evaluate(() => window.generationDemoDebug().result);
  assert.deepEqual(ruins.plan, initial.result.plan, 'contents changes emitted geometry without changing the partition');
  const geometry = value => value.regions.map(r => ({ structures: r.manifest.structures, obstacles: r.manifest.obstacles, elements: r.elements }));
  assert.notDeepEqual(geometry(ruins), geometry(initial.result), 'contents changes physical structures and obstacles');
  await page.getByLabel('Seed').fill('8123'); await page.getByLabel('Seed').press('Enter');
  await page.waitForFunction(() => window.generationDemoDebug().result?.seed === 8123);
  const seeded = await page.evaluate(() => window.generationDemoDebug().result);
  assert.deepEqual(seeded.plan, initial.result.plan, 'seed changes do not recompute a different partition');
  assert.notDeepEqual(geometry(seeded), geometry(ruins), 'seed changes physical geometry');
  const download = page.waitForEvent('download'); await page.getByRole('button', { name: 'Download JSON' }).click(); const file = await download;
  assert.deepEqual(JSON.parse(await readFile(await file.path(), 'utf8')), JSON.parse(JSON.stringify(seeded)), 'download preserves full realized decomposition');
  await page.getByLabel('Example shape').selectOption('neck');
  await page.waitForFunction(() => window.generationDemoDebug().result?.plan.context.id.includes('neck'));
  const corridor = await page.evaluate(() => window.generationDemoDebug().result.assignments.find(a => a.role === 'corridor').pieceId);
  await page.getByLabel('Region assignment').selectOption(corridor);
  await page.getByRole('button', { name: 'Reset walker here' }).click();
  const before = await page.evaluate(() => window.generationDemoDebug().currentPiece);
  await page.locator('#preview').click(); await page.keyboard.down('KeyA');
  await page.waitForFunction(piece => window.generationDemoDebug().currentPiece !== piece, before, { timeout: 7000 });
  await page.keyboard.up('KeyA');
  const after = await page.evaluate(() => window.generationDemoDebug());
  assert.notEqual(after.currentPiece, before, 'WASD crosses from the corridor anchor into another owned child region');
  await page.screenshot({ path: 'test-results/generation-demo.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'mobile demo has no horizontal overflow');
  assert.deepEqual(errors, [], errors.join('\n'));
} finally { await browser.close(); await server.close(); await rm(replayDir, { recursive: true, force: true }); }
