// Developer preview acceptance: run directly with `node tests/micro-lab.mjs`.
import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { chromium } from '@playwright/test';
import { createArenaServer } from '../server/index.js';
import { listen } from './helpers/listen.js';

const replayDir = await mkdtemp(path.join(os.tmpdir(), 'last-exit-micro-lab-'));
await mkdir('test-results', { recursive: true });
const server = await createArenaServer({ replayDir, profileSummary: false });
const base = await listen(server);
const browser = await chromium.launch({ channel: 'chrome', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1200, height: 900 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error' && !message.text().includes('404')) errors.push(message.text()); });
  await page.goto(`${base}/micro-lab.html`);
  await page.waitForFunction(() => window.microLabDebug?.().result, null, { timeout: 15000 });
  assert.equal(errors.length, 0, errors.join('\n'));
  const initial = await page.evaluate(() => window.microLabDebug());
  assert.equal(initial.result.version, 'micro-1');
  assert.equal(initial.result.spec.bodyProfile, 'cell');
  assert.ok(initial.result.manifest.obstacles > 0, 'default builder emits geometry');
  assert.ok(initial.result.ports.length >= 2, 'required west/east ports resolve');
  for (const builder of ['open', 'depot', 'courtyard', 'ruins']) {
    await page.getByLabel('Builder').selectOption(builder);
    await page.getByRole('button', { name: 'Generate region' }).click();
    await page.waitForFunction(name => window.microLabDebug().result?.manifest.builder === name, builder);
    const generated = await page.evaluate(() => window.microLabDebug());
    assert.ok(generated.result.manifest.attempted > generated.result.manifest.rejected, `${builder} places content beyond the port boundary`);
    if (builder === 'depot' || builder === 'courtyard') assert.ok(generated.result.manifest.structures > 0, `${builder} has roofed structures`);
    if (builder === 'depot' || builder === 'courtyard') await page.screenshot({ path: `test-results/micro-lab-${builder}.png` });
  }
  await page.getByLabel('Seed').fill('0');
  await page.getByRole('button', { name: 'Generate region' }).click();
  await page.waitForFunction(() => window.microLabDebug().result?.spec.seed === 0);
  await page.getByLabel('Seed').fill('9961');
  await page.getByLabel('Density').fill('0.9');
  await page.getByLabel('Region shape').selectOption('hole');
  await page.getByLabel('Contestant north port').check();
  await page.getByRole('button', { name: 'Generate region' }).click();
  await page.waitForFunction(() => window.microLabDebug().result?.spec.seed === 9961);
  const varied = await page.evaluate(() => window.microLabDebug());
  assert.notDeepEqual(varied.result.elements, initial.result.elements, 'seed and controls vary output');
  assert.ok(varied.result.ports.some(port => port.id === 'contestant-north'), 'optional north port resolves');
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download JSON' }).click();
  const downloadFile = await download;
  assert.match(downloadFile.suggestedFilename(), /^micro-region-9961\.json$/);
  assert.deepEqual(JSON.parse(await readFile(await downloadFile.path(), 'utf8')), varied.result, 'download preserves the generated artifact');
  const before = varied.avatar.x;
  await page.evaluate(() => document.activeElement?.blur());
  await page.keyboard.down('KeyD');
  await page.waitForFunction(x => window.microLabDebug().avatar.x !== x, before);
  await page.keyboard.up('KeyD');
  const after = await page.evaluate(() => window.microLabDebug().avatar.x);
  assert.notEqual(after, before, `walker should move or slide: ${before} -> ${after}`);
  await page.screenshot({ path: 'test-results/micro-lab.png' });
  await page.getByLabel('Builder', { exact: true }).selectOption('entry');
  assert.equal(await page.getByLabel('Ruin decay').isDisabled(), true, 'ruin-only control is disabled for entry layouts');
  await page.getByRole('button', { name: 'Generate region' }).click();
  await page.waitForFunction(() => window.microLabDebug().result?.entry?.points.length === 24);
  const entry = await page.evaluate(() => window.microLabDebug().result);
  assert.equal(entry.entry.shortfall, 0);
  const entryPoints = entry.entry.points;
  await page.getByLabel('Seed').fill('8128');
  await page.getByRole('button', { name: 'Generate region' }).click();
  await page.waitForFunction(() => window.microLabDebug().result?.spec.seed === 8128);
  assert.notDeepEqual((await page.evaluate(() => window.microLabDebug().result)).entry.points, entryPoints, 'entry seed changes visible position geometry');
  await page.getByLabel('Seed').fill(String(entry.spec.seed));
  await page.getByRole('button', { name: 'Generate region' }).click();
  await page.waitForFunction(seed => window.microLabDebug().result?.spec.seed === seed, entry.spec.seed);
  await page.screenshot({ path: 'test-results/micro-lab-entry.png', fullPage: true });
  await page.locator('#import').setInputFiles({ name: 'entry.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(entry)) });
  await page.waitForFunction(() => document.getElementById('status').textContent.startsWith('Loaded entry.json'));
  assert.deepEqual(await page.evaluate(() => window.microLabDebug().result), entry);
  const invalid = structuredClone(entry); invalid.entry.points[0].x = -999;
  await page.locator('#import').setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(invalid)) });
  await page.waitForFunction(() => document.getElementById('status').textContent.startsWith('Import rejected:'));
  assert.deepEqual(await page.evaluate(() => window.microLabDebug().result), entry, 'bad import preserves the previous valid region');
  await page.getByLabel('Builder', { exact: true }).selectOption('ruins');
  await page.getByLabel('Ruin decay').fill('0');
  await page.waitForFunction(() => window.microLabDebug().result?.spec.parameters.decay === 0);
  const intact = await page.evaluate(() => window.microLabDebug().result.elements);
  await page.screenshot({ path: 'test-results/micro-lab-decay-0.png', fullPage: true });
  await page.getByLabel('Ruin decay').fill('1');
  await page.waitForFunction(() => window.microLabDebug().result?.spec.parameters.decay === 1);
  assert.notDeepEqual(await page.evaluate(() => window.microLabDebug().result.elements), intact, 'decay auto-applies and changes physical geometry');
  await page.screenshot({ path: 'test-results/micro-lab-decay-1.png', fullPage: true });
  await page.getByLabel('Body scale').selectOption('live');
  await page.getByRole('button', { name: 'Generate region' }).click();
  await page.waitForFunction(() => window.microLabDebug().result?.spec.bodyProfile === 'live');
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, 'compact lab has no horizontal overflow');
  assert.equal(errors.length, 0, errors.join('\n'));
} finally {
  await browser.close();
  await server.close();
  await rm(replayDir, { recursive: true, force: true });
}
